if (1 == 1) {
} else {
}
EOF
1	1	KEY_WORD	if	KeyWordType.IF
1	4	SEPARATOR	(	SepType.L_PARENT
1	5	INT	1	1
1	7	OPERATION	==	OpType.EQUALS
1	10	INT	1	1
1	11	SEPARATOR	)	SepType.R_PARENT
1	13	SEPARATOR	{	SepType.L_CURLY
2	1	SEPARATOR	}	SepType.R_CURLY
2	3	KEY_WORD	else	KeyWordType.ELSE
2	8	SEPARATOR	{	SepType.L_CURLY
3	1	SEPARATOR	}	SepType.R_CURLY